[package]
name = "compositions"
version = "0.1.2"
authors = ["Andrey Zabolotskiy"]

[target.'cfg(windows)'.dependencies]
clipboard-win = { version = "5.3", optional = true }

[features]
clip = ["clipboard-win"]
